
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dealership
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

#
#  backend:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: cs631_backend
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/dealership
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"

#  frontend:
#    build:
#      context: ./FE/dealership_front_end
#      dockerfile: Dockerfile
#    container_name: frontend
#    ports:
#      - "5173:80"


volumes:
  mysql_data:

